// dummyData.js
const dummyData = [
  [
    { id: 1, vehicle: '차량1', status: '운행상태', battery: '운행중' },
    { id: 2, vehicle: '차량2', status: '시동상태', battery: 'ON' },
    { id: 3, vehicle: '차량3', status: '통신상태', battery: 'ON' },
    { id: 4, vehicle: '차량1', status: '운행속도', battery: '60 km/시' },
    { id: 5, vehicle: '차량2', status: '주행거리', battery: '20,000km' },
    { id: 6, vehicle: '차량3', status: '위치', battery: '푸르지오.한미약품' },
    { id: 7, vehicle: '차량1', status: '모터정보', battery: 'ON' },
    { id: 8, vehicle: '차량2', status: '배터리SOC', battery: '50%' },
    { id: 9, vehicle: '차량3', status: '배터리온도', battery: '30˚' },
    { id: 10, vehicle: '차량1', status: '배터리HOC', battery: '35%' },
    { id: 11, vehicle: '차량2', status: '보조배터리 전압', battery: '20V' },
    { id: 12, vehicle: '차량3', status: '이벤트발생', battery: 'NO' },
  ],
  [
    { id: 1, vehicle: '차량1', status: '운행상태', battery: '운행중' },
    { id: 2, vehicle: '차량2', status: '시동상태', battery: 'ON' },
    { id: 3, vehicle: '차량3', status: '통신상태', battery: 'ON' },
    { id: 4, vehicle: '차량1', status: '운행속도', battery: '63 km/시' },
    { id: 5, vehicle: '차량2', status: '주행거리', battery: '20,001km' },
    { id: 6, vehicle: '차량3', status: '위치', battery: '상록.테크노밸리.GS자이' },
    { id: 7, vehicle: '차량1', status: '모터정보', battery: 'ON' },
    { id: 8, vehicle: '차량2', status: '배터리SOC', battery: '40%' },
    { id: 9, vehicle: '차량3', status: '배터리온도', battery: '31˚' },
    { id: 10, vehicle: '차량1', status: '배터리HOC', battery: '31%' },
    { id: 11, vehicle: '차량2', status: '보조배터리 전압', battery: '20V' },
    { id: 12, vehicle: '차량3', status: '이벤트발생', battery: 'NO' },
  ],
  [
    { id: 1, vehicle: '차량1', status: '운행상태', battery: '운행중' },
    { id: 2, vehicle: '차량2', status: '시동상태', battery: 'ON' },
    { id: 3, vehicle: '차량3', status: '통신상태', battery: 'ON' },
    { id: 4, vehicle: '차량1', status: '운행속도', battery: '48 km/시' },
    { id: 5, vehicle: '차량2', status: '주행거리', battery: '20,002km' },
    { id: 6, vehicle: '차량3', status: '위치', battery: '우남퍼스트빌.자이' },
    { id: 7, vehicle: '차량1', status: '모터정보', battery: 'ON' },
    { id: 8, vehicle: '차량2', status: '배터리SOC', battery: '38%' },
    { id: 9, vehicle: '차량3', status: '배터리온도', battery: '37˚' },
    { id: 10, vehicle: '차량1', status: '배터리HOC', battery: '32%' },
    { id: 11, vehicle: '차량2', status: '보조배터리 전압', battery: '20V' },
    { id: 12, vehicle: '차량3', status: '이벤트발생', battery: 'NO' },
  ],
  [
    { id: 1, vehicle: '차량1', status: '운행상태', battery: '운행중' },
    { id: 2, vehicle: '차량2', status: '시동상태', battery: 'ON' },
    { id: 3, vehicle: '차량3', status: '통신상태', battery: 'ON' },
    { id: 4, vehicle: '차량1', status: '운행속도', battery: '51 km/시' },
    { id: 5, vehicle: '차량2', status: '주행거리', battery: '20,003km' },
    { id: 6, vehicle: '차량3', status: '위치', battery: '우남퍼스트빌.자이' },
    { id: 7, vehicle: '차량1', status: '모터정보', battery: 'ON' },
    { id: 8, vehicle: '차량2', status: '배터리SOC', battery: '35%' },
    { id: 9, vehicle: '차량3', status: '배터리온도', battery: '35˚' },
    { id: 10, vehicle: '차량1', status: '배터리HOC', battery: '34%' },
    { id: 11, vehicle: '차량2', status: '보조배터리 전압', battery: '20V' },
    { id: 12, vehicle: '차량3', status: '이벤트발생', battery: 'NO' },
  ],
  [
    { id: 1, vehicle: '차량1', status: '운행상태', battery: '운행중' },
    { id: 2, vehicle: '차량2', status: '시동상태', battery: 'ON' },
    { id: 3, vehicle: '차량3', status: '통신상태', battery: 'ON' },
    { id: 4, vehicle: '차량1', status: '운행속도', battery: '49 km/시' },
    { id: 5, vehicle: '차량2', status: '주행거리', battery: '20,004km' },
    { id: 6, vehicle: '차량3', status: '위치', battery: '우남퍼스트빌.자이' },
    { id: 7, vehicle: '차량1', status: '모터정보', battery: 'ON' },
    { id: 8, vehicle: '차량2', status: '배터리SOC', battery: '33%' },
    { id: 9, vehicle: '차량3', status: '배터리온도', battery: '34˚' },
    { id: 10, vehicle: '차량1', status: '배터리HOC', battery: '32%' },
    { id: 11, vehicle: '차량2', status: '보조배터리 전압', battery: '20V' },
    { id: 12, vehicle: '차량3', status: '이벤트발생', battery: 'NO' },
  ],
  [
    { id: 1, vehicle: '차량1', status: '운행상태', battery: '운행중' },
    { id: 2, vehicle: '차량2', status: '시동상태', battery: 'ON' },
    { id: 3, vehicle: '차량3', status: '통신상태', battery: 'ON' },
    { id: 4, vehicle: '차량1', status: '운행속도', battery: '42 km/시' },
    { id: 5, vehicle: '차량2', status: '주행거리', battery: '20,005km' },
    { id: 6, vehicle: '차량3', status: '위치', battery: '우남퍼스트빌.자이' },
    { id: 7, vehicle: '차량1', status: '모터정보', battery: 'ON' },
    { id: 8, vehicle: '차량2', status: '배터리SOC', battery: '30%' },
    { id: 9, vehicle: '차량3', status: '배터리온도', battery: '35˚' },
    { id: 10, vehicle: '차량1', status: '배터리HOC', battery: '34%' },
    { id: 11, vehicle: '차량2', status: '보조배터리 전압', battery: '20V' },
    { id: 12, vehicle: '차량3', status: '이벤트발생', battery: 'NO' },
  ],
];

export default dummyData;
